name: build.yml
on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CI=ON
        name: Generate Build Scripts
      - run: cmake --build build --config Release
        name: Build Project
      - uses: actions/upload-artifact@v4
        with:
          name: 'binaries-${{ matrix.os }}'
          path: build/output
