# SPDX-FileCopyrightText: 2025 CelDaemon <celdaemon@voidgroup.net>
# SPDX-License-Identifier: BSD-3-Clause

name: reuse.yml
on:
  push:

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository
      - run: sudo apt install reuse
        name: Install Reuse
      - run: reuse lint
        name: Check Reuse Conformance
